### ISSUE TITLE
RLS error on lamin init with S3 path

### ISSUE THREAD

**Issue by ShuhengZhao-creator** [laminlabs/lamindb#2752]
### Add a description
 **lamin init --storage s3:...  --modules bionty**
![Image](https://github.com/user-attachments/assets/0485d14c-eb25-4471-9e54-6066bc9f0dbf)

**Comment by Koncopd** [comment]
Hello, @ShuhengZhao-creator . This error says that the s3 path you are trying to use (or its parent or child) is already registered.

**Comment by ShuhengZhao-creator** [comment]
> Hello, [@ShuhengZhao-creator](https://github.com/ShuhengZhao-creator) . This error says that the s3 path you are trying to use (or its parent or child) is already registered.

Thank you，How can I find registered paths and delete them？

**Comment by Koncopd** [comment]
We don't have a way for this now, you can say me the bucket and i will write what we have for it.

**Comment by Koncopd** [comment]
`s3://cartabio/ai/data/fujing_test2/d209ed8a81c95e5eb996e12ec649f88d.lndb`
I see this already, which is strange, because it should not be a path to a file, just to a bucket or its subfolders. Should i delete?

**Comment by ShuhengZhao-creator** [comment]
> `s3://cartabio/ai/data/fujing_test2/d209ed8a81c95e5eb996e12ec649f88d.lndb` I see this already, which is strange, because it should not be a path to a file, just to a bucket or its subfolders. Should i delete?

Thank you [Koncopd](https://github.com/Koncopd)，This seems to be an instance of my previous incorrect init，I want to delete it

**Comment by Koncopd** [comment]
done

**Comment by ShuhengZhao-creator** [comment]
> done
lamin init --storage s3://cartabio/ai/data/lamin1_5 --schema bionty ，The same error will still occur

**Comment by Koncopd** [comment]
Let me check again.

**Comment by Koncopd** [comment]
Ok, there is already a registered path `s3://cartabio/ai/data` for instance `data` by the user `kang`, so you can't register any children or parents of this storage. We will improve the error to show which registered paths prevent from registering a new path.

You can register with `s3://cartabio/ai/lamin1_5/`, for example, if it is available.

**Comment by ShuhengZhao-creator** [comment]
> Ok, there is already a registered path `s3://cartabio/ai/data` for instance `data` by the user `kang`, so you can't register any children or parents of this storage. We will improve the error to show which registered paths prevent from registering a new path.
> 
> You can register with `s3://cartabio/ai/lamin1_5/`, for example, if it is available.

Thank you very much [Koncopd](https://github.com/Koncopd)！
